services:
    app:
        build: .
        container_name: laravel_app
        restart: always
        volumes:
            - .:/var/www

    nginx:
        image: nginx:alpine
        container_name: laravel_nginx
        restart: always
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
            - ./docker/default.conf:/etc/nginx/conf.d/default.conf
