openapi: 3.0.3
info:
  title: 'Wallex interview task api'
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost:8000'
paths:
  /api/machines:
    get:
      summary: ''
      operationId: getApiMachines
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    -
                      id: 1
                      name: 'Machine 1'
                      balance: 0
                      state: App\States\IdleState
                      products:
                        -
                          id: 1
                          name: coffee
                          stock: 10
                          price: 1
                        -
                          id: 2
                          name: soda
                          stock: 15
                          price: 2
                properties:
                  data:
                    type: array
                    example:
                      -
                        id: 1
                        name: 'Machine 1'
                        balance: 0
                        state: App\States\IdleState
                        products:
                          -
                            id: 1
                            name: coffee
                            stock: 10
                            price: 1
                          -
                            id: 2
                            name: soda
                            stock: 15
                            price: 2
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 1
                        name:
                          type: string
                          example: 'Machine 1'
                        balance:
                          type: integer
                          example: 0
                        state:
                          type: string
                          example: App\States\IdleState
                        products:
                          type: array
                          example:
                            -
                              id: 1
                              name: coffee
                              stock: 10
                              price: 1
                            -
                              id: 2
                              name: soda
                              stock: 15
                              price: 2
                          items:
                            type: object
                            properties:
                              id:
                                type: integer
                                example: 1
                              name:
                                type: string
                                example: coffee
                              stock:
                                type: integer
                                example: 10
                              price:
                                type: integer
                                example: 1
      tags:
        - Endpoints
      security: []
  '/api/machines/{machine_id}/insert-coin':
    post:
      summary: ''
      operationId: postApiMachinesMachine_idInsertCoin
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                amount:
                  type: number
                  description: ''
                  example: 46027499.753685
                  nullable: false
              required:
                - amount
      security: []
    parameters:
      -
        in: path
        name: machine_id
        description: 'The ID of the machine.'
        example: 1
        required: true
        schema:
          type: integer
  '/api/machines/{machine_id}/select-product/{product_id}':
    post:
      summary: ''
      operationId: postApiMachinesMachine_idSelectProductProduct_id
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: machine_id
        description: 'The ID of the machine.'
        example: 1
        required: true
        schema:
          type: integer
      -
        in: path
        name: product_id
        description: 'The ID of the product.'
        example: 1
        required: true
        schema:
          type: integer
  '/api/machines/{machine_id}/dispense':
    post:
      summary: ''
      operationId: postApiMachinesMachine_idDispense
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: machine_id
        description: 'The ID of the machine.'
        example: 1
        required: true
        schema:
          type: integer
tags:
  -
    name: Endpoints
    description: ''
